type IngredientsType = {
    Chicken: number
    Salmon: number
    Beef: number
    Pork: number
    Avocado: number
    Apple_Cider_Vinegar: number
    Asparagus: number
    Aubergine: number
    Baby_Plum_Tomatoes: number
    Bacon: number
    Baking_Powder: number
    Balsamic_Vinegar: number
    Basil: number
    Basil_Leaves: number
    Basmati_Rice: number
    Bay_Leaf: number
    Bay_Leaves: number
    Beef_Brisket: number
    Beef_Fillet: number
    Beef_Gravy: number
    Beef_Stock: number
    Bicarbonate_Of_Soda: number
    Biryani_Masala: number
    Black_Pepper: number
    Black_Treacle: number
    Borlotti_Beans: number
    Bowtie_Pasta: number
    Bramley_Apples: number
    Brandy: number
    Bread: number
    Breadcrumbs: number
    Broccoli: number
    Brown_Lentils: number
    Brown_Rice: number
    Brown_Sugar: number
    Butter: number
    Cacao: number
    Cajun: number
    Canned_Tomatoes: number
    Cannellini_Beans: number
    Cardamom: number
    Carrots: number
    Cashew_Nuts: number
    Cashews: number
    Caster_Sugar: number
    Cayenne_Pepper: number
    Celeriac: number
    Celery: number
    Celery_Salt: number
    Challots: number
    Charlotte_Potatoes: number
    Cheddar_Cheese: number
    Cheese: number
    Cheese_Curds: number
    Cherry_Tomatoes: number
    Chestnut_Mushroom: number
    Chicken_Breast: number
    Chicken_Breasts: number
    Chicken_Legs: number
    Chicken_Stock: number
    Chicken_Thighs: number
    Chickpeas: number
    Chili_Powder: number
    Chilled_Butter: number
    Chilli: number
    Chilli_Powder: number
    Chinese_Broccoli: number
    Chocolate_Chips: number
    Chopped_Onion: number
    Chopped_Parsley: number
    Chopped_Tomatoes: number
    Chorizo: number
    Christmas_Pudding: number
    Cilantro: number
    Cinnamon: number
    Cinnamon_Stick: number
    Cloves: number
    Coco_Sugar: number
    Cocoa: number
    Coconut_Cream: number
    Coconut_Milk: number
    Colby_Jack_Cheese: number
    Cold_Water: number
    Condensed_Milk: number
    Coriander: number
    Coriander_Leaves: number
    Coriander_Seeds: number
    Corn_Tortillas: number
    Cornstarch: number
    Cream: number
    Creme_Fraiche: number
    Cubed_Feta_Cheese: number
    Cucumber: number
    Cumin: number
    Cumin_Seeds: number
    Curry_Powder: number
    Dark_Brown_Sugar: number
    Dark_Soft_Brown_Sugar: number
    Dark_Soy_Sauce: number
    Demerara_Sugar: number
    Diced_Tomatoes: number
    Digestive_Biscuits: number
    Dill: number
    Doner_Meat: number
    Double_Cream: number
    Dried_Oregano: number
    Dry_White_Wine: number
    Egg_Plants: number
    Egg_Rolls: number
    Egg_White: number
    Egg_Yolks: number
    Eggs: number
    Enchilada_Sauce: number
    English_Mustard: number
    Extra_Virgin_Olive_Oil: number
    Fajita_Seasoning: number
    Farfalle: number
    Fennel_Bulb: number
    Fennel_Seeds: number
    Fenugreek: number
    Feta: number
    Fish_Sauce: number
    Flaked_Almonds: number
    Flax_Eggs: number
    Flour: number
    Flour_Tortilla: number
    Floury_Potatoes: number
    French_Lentils: number
    Fresh_Basil: number
    Fresh_Thyme: number
    Freshly_Chopped_Parsley: number
    Fries: number
    Full_Fat_Yogurt: number
    Garam_Masala: number
    Garlic: number
    Garlic_Clove: number
    Garlic_Powder: number
    Garlic_Sauce: number
    Ghee: number
    Ginger: number
    Ginger_Cordial: number
    Ginger_Garlic_Paste: number
    Ginger_Paste: number
    Golden_Syrup: number
    Gouda_Cheese: number
    Granulated_Sugar: number
    Grape_Tomatoes: number
    Greek_Yogurt: number
    Green_Beans: number
    Green_Chilli: number
    Green_Olives: number
    Green_Red_Lentils: number
    Green_Salsa: number
    Ground_Almonds: number
    Ground_Cumin: number
    Ground_Ginger: number
    Gruyère: number
    Hard_Taco_Shells: number
    Harissa_Spice: number
    Heavy_Cream: number
    Honey: number
    Horseradish: number
    Hot_Beef_Stock: number
    Hotsauce: number
    Ice_Cream: number
    Italian_Fennel_Sausages: number
    Italian_Seasoning: number
    Jalapeno: number
    Jasmine_Rice: number
    Jerusalem_Artichokes: number
    Kale: number
    Khus_Khus: number
    King_Prawns: number
    Kosher_Salt: number
    Lamb: number
    Lamb_Loin_Chops: number
    Lamb_Mince: number
    Lasagne_Sheets: number
    Lean_Minced_Beef: number
    Leek: number
    Lemon: number
    Lemon_Juice: number
    Lemon_Zest: number
    Lemons: number
    Lettuce: number
    Lime: number
    Little_Gem_Lettuce: number
    Macaroni: number
    Mackerel: number
    Madras_Paste: number
    Marjoram: number
    Massaman_Curry_Paste: number
    Medjool_Dates: number
    Meringue_Nests: number
    Milk: number
    Minced_Garlic: number
    Miniature_Marshmallows: number
    Mint: number
    Monterey_Jack_Cheese: number
    Mozzarella_Balls: number
    Muscovado_Sugar: number
    Mushrooms: number
    Mustard: number
    Mustard_Powder: number
    Mustard_Seeds: number
    Nutmeg: number
    Oil: number
    Olive_Oil: number
    Onion_Salt: number
    Onions: number
    Orange: number
    Orange_Zest: number
    Oregano: number
    Oyster_Sauce: number
    Paprika: number
    Parma_Ham: number
    Parmesan: number
    Parmesan_Cheese: number
    // Parmigiano-reggiano: number
    Parsley: number
    Peanut_Butter: number
    Peanut_Oil: number
    Peanuts: number
    Peas: number
    Pecorino: number
    Penne_Rigate: number
    Pepper: number
    Pine_Nuts: number
    Pitted_Black_Olives: number
    Plain_Chocolate: number
    Plain_Flour: number
    Plum_Tomatoes: number
    Potato_Starch: number
    Potatoes: number
    Prawns: number
    Puff_Pastry: number
    Raspberry_Jam: number
    Raw_King_Prawns: number
    Red_Chile_Flakes: number
    Red_Chilli: number
    Red_Chilli_Powder: number
    Red_Onions: number
    Red_Pepper: number
    Red_Pepper_Flakes: number
    Red_Wine: number
    Refried_Beans: number
    Rice: number
    Rice_Noodles: number
    Rice_Stick_Noodles: number
    Rice_Vermicelli: number
    Rigatoni: number
    Rocket: number
    Rolled_Oats: number
    Saffron: number
    Sage: number
    Sake: number
    Salsa: number
    Salt: number
    Salted_Butter: number
    Sausages: number
    Sea_Salt: number
    // Self-raising_Flour: number
    // Semi-skimmed_Milk
    Sesame_Seed: number
    Shallots: number
    Shredded_Mexican_Cheese: number
    Shredded_Monterey_Jack_Cheese: number
    Small_Potatoes: number
    Smoked_Paprika: number
    Smoky_Paprika: number
    Sour_Cream: number
    Soy_Sauce: number
    Soya_Milk: number
    Spaghetti: number
    Spinach: number
    Spring_Onions: number
    Squash: number
    // Stir-fry_Vegetables
    Strawberries: number
    Sugar: number
    Sultanas: number
    Sunflower_Oil: number
    Tamarind_Ball: number
    Tamarind_Paste: number
    Thai_Fish_Sauce: number
    Thai_Green_Curry_Paste: number
    Thai_Red_Curry_Paste: number
    Thyme: number
    Tomato_Ketchup: number
    Tomato_Puree: number
    Tomatoes: number
    Toor_Dal: number
    Tuna: number
    Turmeric: number
    Turmeric_Powder: number
    Turnips: number
    Vanilla: number
    Vanilla_Extract: number
    Veal: number
    Vegan_Butter: number
    Vegetable_Oil: number
    Vegetable_Stock: number
    Vegetable_Stock_Cube: number
    Vinaigrette_Dressing: number
    Vine_Leaves: number
    Vinegar: number
    Water: number
    White_Chocolate_Chips: number
    White_Fish: number
    White_Fish_Fillets: number
    White_Vinegar: number
    White_Wine: number
    Whole_Milk: number
    Whole_Wheat: number
    Wholegrain_Bread: number
    Worcestershire_Sauce: number
    Yogurt: number
    Zucchini: number
    Pretzels: number
    Cream_Cheese: number
    Icing_Sugar: number
    Toffee_Popcorn: number
    Caramel: number
    Caramel_Sauce: number
    Tagliatelle: number
    Fettuccine: number
    Clotted_Cream: number
    Corn_Flour: number
    Mussels: number
    Fideo: number
    Monkfish: number
    Vermicelli_Pasta: number
    Baby_Squid: number
    Squid: number
    Fish_Stock: number
    Pilchards: number
    Black_Olives: number
    Onion: number
    Tomato: number
    Duck: number
    Duck_Legs: number
    Chicken_Stock_Cube: number
    Pappardelle_Pasta: number
    Paccheri_Pasta: number
    Linguine_Pasta: number
    Sugar_Snap_Peas: number
    Crusty_Bread: number
    Fromage_Frais: number
    Clams: number
    Passata: number
    Rapeseed_Oil: number
    Stilton_Cheese: number
    Lamb_Leg: number
    Lamb_Shoulder: number
    Apricot: number
    Butternut_Squash: number
    Couscous: number
    Minced_Beef: number
    Turkey_Mince: number
    Barbeque_Sauce: number
    Sweetcorn: number
    Goose_Fat: number
    Duck_Fat: number
    Fennel: number
    Red_Wine_Vinegar: number
    Haricot_Beans: number
    Rosemary: number
    Butter_Beans: number
    Pinto_Beans: number
    Tomato_Sauce: number
    Mascarpone: number
    Mozzarella: number
    Ricotta: number
    Dried_Apricots: number
    Capers: number
    Banana: number
    Raspberries: number
    Blueberries: number
    Walnuts: number
    Pecan_Nuts: number
    Maple_Syrup: number
    Light_Brown_Soft_Sugar: number
    Dark_Brown_Soft_Sugar: number
    Dark_Chocolate_Chips: number
    Milk_Chocolate: number
    Dark_Chocolate: number
    Pumpkin: number
    Shortcrust_Pastry: number
    Peanut_Cookies: number
    Gelatine_Leafs: number
    Peanut_Brittle: number
    Peaches: number
    Yellow_Pepper: number
    Green_Pepper: number
    Courgettes: number
    Tinned_Tomatos: number
    Chestnuts: number
    Wild_Mushrooms: number
    Truffle_Oil: number
    Paneer: number
    Naan_Bread: number
    Lentils: number
    Roasted_Vegetables: number
    Kidney_Beans: number
    Mixed_Grain: number
    Tahini: number
    Tortillas: number
    Udon_Noodles: number
    Cabbage: number
    Shiitake_Mushrooms: number
    Mirin: number
    Sesame_Seed_Oil: number
    Baguette: number
    Vine_Tomatoes: number
    Suet: number
    Swede: number
    Ham: number
    Oysters: number
    Stout: number
    Lard: number
    Lamb_Kidney: number
    Beef_Kidney: number
    Haddock: number
    Smoked_Haddock: number
    Brussels_Sprouts: number
    Raisins: number
    Currants: number
    Custard: number
    Mixed_Peel: number
    Redcurrants: number
    Blackberries: number
    Hazlenuts: number
    Braeburn_Apples: number
    Red_Food_Colouring: number
    Pink_Food_Colouring: number
    Blue_Food_Colouring: number
    Yellow_Food_Colouring: number
    Apricot_Jam: number
    Marzipan: number
    Almonds: number
    Black_Pudding: number
    Baked_Beans: number
    White_Flour: number
    Yeast: number
    Fruit_Mix: number
    Dried_Fruit: number
    Cherry: number
    Glace_Cherry: number
    Treacle: number
    Oatmeal: number
    Oats: number
    Egg: number
    Beef_Shin: number
    Bouquet_Garni: number
    Single_Cream: number
    Red_Wine_Jelly: number
    Apples: number
    Goats_Cheese: number
    Prosciutto: number
    Unsalted_Butter: number
    Brie: number
    Tarragon_Leaves: number
    Chives: number
    Pears: number
    White_Chocolate: number
    Star_Anise: number
    Tiger_Prawns: number
    Custard_Powder: number
    Desiccated_Coconut: number
    Frozen_Peas: number
    Minced_Pork: number
    Creamed_Corn: number
    // Sun-Dried_Tomatoes: number
    Dijon_Mustard: number
    Tabasco_Sauce: number
    Canola_Oil: number
    Cod: number
    Salt_Cod: number
    Ackee: number
    Jerk: number
    Ground_Beef: number
    Baby_Aubergine: number
    Paella_Rice: number
    Scotch_Bonnet: number
    Oxtail: number
    Broad_Beans: number
    Red_Snapper: number
    Malt_Vinegar: number
    Rice_Vinegar: number
    Water_Chestnut: number
    Tofu: number
    Doubanjiang: number
    Fermented_Black_Beans: number
    Scallions: number
    Sichuan_Pepper: number
    Wonton_Skin: number
    Starch: number
    Rice_wine: number
    Cooking_wine: number
    Duck_Sauce: number
    Gochujang: number
    Bean_Sprouts: number
    Noodles: number
    Wood_Ear_Mushrooms: number
    Dark_Rum: number
    Light_Rum: number
    Rum: number
    English_Muffins: number
    Muffins: number
    White_Wine_Vinegar: number
    Smoked_Salmon: number
    Mars_Bar: number
    Rice_Krispies: number
    Ancho_Chillies: number
    Almond_Milk: number
    Allspice: number
    Almond_Extract: number
    Tripe: number
    Goat_Meat: number
    Black_Beans: number
    Anchovy_Fillet: number
    Ras_el_hanout: number
    Filo_Pastry: number
    Orange_Blossom_Water: number
    Candied_Peel: number
    Grand_Marnier: number
    Sherry: number
    Rose_water: number
    Mixed_Spice: number
    Mincemeat: number
    Sweet_Potatoes: number
    Bread_Rolls: number
    Bun: number
    Potatoe_Buns: number
    Ground_Pork: number
    Pork_Chops: number
    Yukon_Gold_Potatoes: number
    Yellow_Onion: number
    Beef_Stock_Concentrate: number
    Chicken_Stock_Concentrate: number
    Persian_Cucumber: number
    Mayonnaise: number
    Sriracha: number
    Rhubarb: number
    Pita_Bread: number
    Bulgur_Wheat: number
    Quinoa: number
    Dill_Pickles: number
    Sesame_Seed_Burger_Buns: number
    Buns: number
    Iceberg_Lettuce: number
    Gherkin_Relish: number
    Cheese_Slices: number
    Shortening: number
    Warm_Water: number
    Boiling_Water: number
    Pickle_Juice: number
    Powdered_Sugar: number
    Kielbasa: number
    Polish_Sausage: number
    Sauerkraut: number
    Caraway_Seed: number
    Herring: number
    Jam: number
    Mulukhiyah: number
    Sushi_Rice: number
    Figs: number
    Cider: number
    Beetroot: number
    Sardines: number
    Ciabatta: number
    Buckwheat: number
}

const initStateForIngredients : IngredientsType = {
    Chicken: 0,
    Salmon: 0,
    Beef: 0,
    Pork: 0,
    Avocado: 0,
    Apple_Cider_Vinegar: 0,
    Asparagus: 0,
    Aubergine: 0,
    Baby_Plum_Tomatoes: 0,
    Bacon: 0,
    Baking_Powder: 0,
    Balsamic_Vinegar: 0,
    Basil: 0,
    Basil_Leaves: 0,
    Basmati_Rice: 0,
    Bay_Leaf: 0,
    Bay_Leaves: 0,
    Beef_Brisket: 0,
    Beef_Fillet: 0,
    Beef_Gravy: 0,
    Beef_Stock: 0,
    Bicarbonate_Of_Soda: 0,
    Biryani_Masala: 0,
    Black_Pepper: 0,
    Black_Treacle: 0,
    Borlotti_Beans: 0,
    Bowtie_Pasta: 0,
    Bramley_Apples: 0,
    Brandy: 0,
    Bread: 0,
    Breadcrumbs: 0,
    Broccoli: 0,
    Brown_Lentils: 0,
    Brown_Rice: 0,
    Brown_Sugar: 0,
    Butter: 0,
    Cacao: 0,
    Cajun: 0,
    Canned_Tomatoes: 0,
    Cannellini_Beans: 0,
    Cardamom: 0,
    Carrots: 0,
    Cashew_Nuts: 0,
    Cashews: 0,
    Caster_Sugar: 0,
    Cayenne_Pepper: 0,
    Celeriac: 0,
    Celery: 0,
    Celery_Salt: 0,
    Challots: 0,
    Charlotte_Potatoes: 0,
    Cheddar_Cheese: 0,
    Cheese: 0,
    Cheese_Curds: 0,
    Cherry_Tomatoes: 0,
    Chestnut_Mushroom: 0,
    Chicken_Breast: 0,
    Chicken_Breasts: 0,
    Chicken_Legs: 0,
    Chicken_Stock: 0,
    Chicken_Thighs: 0,
    Chickpeas: 0,
    Chili_Powder: 0,
    Chilled_Butter: 0,
    Chilli: 0,
    Chilli_Powder: 0,
    Chinese_Broccoli: 0,
    Chocolate_Chips: 0,
    Chopped_Onion: 0,
    Chopped_Parsley: 0,
    Chopped_Tomatoes: 0,
    Chorizo: 0,
    Christmas_Pudding: 0,
    Cilantro: 0,
    Cinnamon: 0,
    Cinnamon_Stick: 0,
    Cloves: 0,
    Coco_Sugar: 0,
    Cocoa: 0,
    Coconut_Cream: 0,
    Coconut_Milk: 0,
    Colby_Jack_Cheese: 0,
    Cold_Water: 0,
    Condensed_Milk: 0,
    Coriander: 0,
    Coriander_Leaves: 0,
    Coriander_Seeds: 0,
    Corn_Tortillas: 0,
    Cornstarch: 0,
    Cream: 0,
    Creme_Fraiche: 0,
    Cubed_Feta_Cheese: 0,
    Cucumber: 0,
    Cumin: 0,
    Cumin_Seeds: 0,
    Curry_Powder: 0,
    Dark_Brown_Sugar: 0,
    Dark_Soft_Brown_Sugar: 0,
    Dark_Soy_Sauce: 0,
    Demerara_Sugar: 0,
    Diced_Tomatoes: 0,
    Digestive_Biscuits: 0,
    Dill: 0,
    Doner_Meat: 0,
    Double_Cream: 0,
    Dried_Oregano: 0,
    Dry_White_Wine: 0,
    Egg_Plants: 0,
    Egg_Rolls: 0,
    Egg_White: 0,
    Egg_Yolks: 0,
    Eggs: 0,
    Enchilada_Sauce: 0,
    English_Mustard: 0,
    Extra_Virgin_Olive_Oil: 0,
    Fajita_Seasoning: 0,
    Farfalle: 0,
    Fennel_Bulb: 0,
    Fennel_Seeds: 0,
    Fenugreek: 0,
    Feta: 0,
    Fish_Sauce: 0,
    Flaked_Almonds: 0,
    Flax_Eggs: 0,
    Flour: 0,
    Flour_Tortilla: 0,
    Floury_Potatoes: 0,
    French_Lentils: 0,
    Fresh_Basil: 0,
    Fresh_Thyme: 0,
    Freshly_Chopped_Parsley: 0,
    Fries: 0,
    Full_Fat_Yogurt: 0,
    Garam_Masala: 0,
    Garlic: 0,
    Garlic_Clove: 0,
    Garlic_Powder: 0,
    Garlic_Sauce: 0,
    Ghee: 0,
    Ginger: 0,
    Ginger_Cordial: 0,
    Ginger_Garlic_Paste: 0,
    Ginger_Paste: 0,
    Golden_Syrup: 0,
    Gouda_Cheese: 0,
    Granulated_Sugar: 0,
    Grape_Tomatoes: 0,
    Greek_Yogurt: 0,
    Green_Beans: 0,
    Green_Chilli: 0,
    Green_Olives: 0,
    Green_Red_Lentils: 0,
    Green_Salsa: 0,
    Ground_Almonds: 0,
    Ground_Cumin: 0,
    Ground_Ginger: 0,
    Gruyère: 0,
    Hard_Taco_Shells: 0,
    Harissa_Spice: 0,
    Heavy_Cream: 0,
    Honey: 0,
    Horseradish: 0,
    Hot_Beef_Stock: 0,
    Hotsauce: 0,
    Ice_Cream: 0,
    Italian_Fennel_Sausages: 0,
    Italian_Seasoning: 0,
    Jalapeno: 0,
    Jasmine_Rice: 0,
    Jerusalem_Artichokes: 0,
    Kale: 0,
    Khus_Khus: 0,
    King_Prawns: 0,
    Kosher_Salt: 0,
    Lamb: 0,
    Lamb_Loin_Chops: 0,
    Lamb_Mince: 0,
    Lasagne_Sheets: 0,
    Lean_Minced_Beef: 0,
    Leek: 0,
    Lemon: 0,
    Lemon_Juice: 0,
    Lemon_Zest: 0,
    Lemons: 0,
    Lettuce: 0,
    Lime: 0,
    Little_Gem_Lettuce: 0,
    Macaroni: 0,
    Mackerel: 0,
    Madras_Paste: 0,
    Marjoram: 0,
    Massaman_Curry_Paste: 0,
    Medjool_Dates: 0,
    Meringue_Nests: 0,
    Milk: 0,
    Minced_Garlic: 0,
    Miniature_Marshmallows: 0,
    Mint: 0,
    Monterey_Jack_Cheese: 0,
    Mozzarella_Balls: 0,
    Muscovado_Sugar: 0,
    Mushrooms: 0,
    Mustard: 0,
    Mustard_Powder: 0,
    Mustard_Seeds: 0,
    Nutmeg: 0,
    Oil: 0,
    Olive_Oil: 0,
    Onion_Salt: 0,
    Onions: 0,
    Orange: 0,
    Orange_Zest: 0,
    Oregano: 0,
    Oyster_Sauce: 0,
    Paprika: 0,
    Parma_Ham: 0,
    Parmesan: 0,
    Parmesan_Cheese: 0,
    // Parmigiano-reggiano: 0,
    Parsley: 0,
    Peanut_Butter: 0,
    Peanut_Oil: 0,
    Peanuts: 0,
    Peas: 0,
    Pecorino: 0,
    Penne_Rigate: 0,
    Pepper: 0,
    Pine_Nuts: 0,
    Pitted_Black_Olives: 0,
    Plain_Chocolate: 0,
    Plain_Flour: 0,
    Plum_Tomatoes: 0,
    Potato_Starch: 0,
    Potatoes: 0,
    Prawns: 0,
    Puff_Pastry: 0,
    Raspberry_Jam: 0,
    Raw_King_Prawns: 0,
    Red_Chile_Flakes: 0,
    Red_Chilli: 0,
    Red_Chilli_Powder: 0,
    Red_Onions: 0,
    Red_Pepper: 0,
    Red_Pepper_Flakes: 0,
    Red_Wine: 0,
    Refried_Beans: 0,
    Rice: 0,
    Rice_Noodles: 0,
    Rice_Stick_Noodles: 0,
    Rice_Vermicelli: 0,
    Rigatoni: 0,
    Rocket: 0,
    Rolled_Oats: 0,
    Saffron: 0,
    Sage: 0,
    Sake: 0,
    Salsa: 0,
    Salt: 0,
    Salted_Butter: 0,
    Sausages: 0,
    Sea_Salt: 0,
    // Self-raising_Flour: 0,
    // Semi-skimmed_Milk
    Sesame_Seed: 0,
    Shallots: 0,
    Shredded_Mexican_Cheese: 0,
    Shredded_Monterey_Jack_Cheese: 0,
    Small_Potatoes: 0,
    Smoked_Paprika: 0,
    Smoky_Paprika: 0,
    Sour_Cream: 0,
    Soy_Sauce: 0,
    Soya_Milk: 0,
    Spaghetti: 0,
    Spinach: 0,
    Spring_Onions: 0,
    Squash: 0,
    // Stir-fry_Vegetables
    Strawberries: 0,
    Sugar: 0,
    Sultanas: 0,
    Sunflower_Oil: 0,
    Tamarind_Ball: 0,
    Tamarind_Paste: 0,
    Thai_Fish_Sauce: 0,
    Thai_Green_Curry_Paste: 0,
    Thai_Red_Curry_Paste: 0,
    Thyme: 0,
    Tomato_Ketchup: 0,
    Tomato_Puree: 0,
    Tomatoes: 0,
    Toor_Dal: 0,
    Tuna: 0,
    Turmeric: 0,
    Turmeric_Powder: 0,
    Turnips: 0,
    Vanilla: 0,
    Vanilla_Extract: 0,
    Veal: 0,
    Vegan_Butter: 0,
    Vegetable_Oil: 0,
    Vegetable_Stock: 0,
    Vegetable_Stock_Cube: 0,
    Vinaigrette_Dressing: 0,
    Vine_Leaves: 0,
    Vinegar: 0,
    Water: 0,
    White_Chocolate_Chips: 0,
    White_Fish: 0,
    White_Fish_Fillets: 0,
    White_Vinegar: 0,
    White_Wine: 0,
    Whole_Milk: 0,
    Whole_Wheat: 0,
    Wholegrain_Bread: 0,
    Worcestershire_Sauce: 0,
    Yogurt: 0,
    Zucchini: 0,
    Pretzels: 0,
    Cream_Cheese: 0,
    Icing_Sugar: 0,
    Toffee_Popcorn: 0,
    Caramel: 0,
    Caramel_Sauce: 0,
    Tagliatelle: 0,
    Fettuccine: 0,
    Clotted_Cream: 0,
    Corn_Flour: 0,
    Mussels: 0,
    Fideo: 0,
    Monkfish: 0,
    Vermicelli_Pasta: 0,
    Baby_Squid: 0,
    Squid: 0,
    Fish_Stock: 0,
    Pilchards: 0,
    Black_Olives: 0,
    Onion: 0,
    Tomato: 0,
    Duck: 0,
    Duck_Legs: 0,
    Chicken_Stock_Cube: 0,
    Pappardelle_Pasta: 0,
    Paccheri_Pasta: 0,
    Linguine_Pasta: 0,
    Sugar_Snap_Peas: 0,
    Crusty_Bread: 0,
    Fromage_Frais: 0,
    Clams: 0,
    Passata: 0,
    Rapeseed_Oil: 0,
    Stilton_Cheese: 0,
    Lamb_Leg: 0,
    Lamb_Shoulder: 0,
    Apricot: 0,
    Butternut_Squash: 0,
    Couscous: 0,
    Minced_Beef: 0,
    Turkey_Mince: 0,
    Barbeque_Sauce: 0,
    Sweetcorn: 0,
    Goose_Fat: 0,
    Duck_Fat: 0,
    Fennel: 0,
    Red_Wine_Vinegar: 0,
    Haricot_Beans: 0,
    Rosemary: 0,
    Butter_Beans: 0,
    Pinto_Beans: 0,
    Tomato_Sauce: 0,
    Mascarpone: 0,
    Mozzarella: 0,
    Ricotta: 0,
    Dried_Apricots: 0,
    Capers: 0,
    Banana: 0,
    Raspberries: 0,
    Blueberries: 0,
    Walnuts: 0,
    Pecan_Nuts: 0,
    Maple_Syrup: 0,
    Light_Brown_Soft_Sugar: 0,
    Dark_Brown_Soft_Sugar: 0,
    Dark_Chocolate_Chips: 0,
    Milk_Chocolate: 0,
    Dark_Chocolate: 0,
    Pumpkin: 0,
    Shortcrust_Pastry: 0,
    Peanut_Cookies: 0,
    Gelatine_Leafs: 0,
    Peanut_Brittle: 0,
    Peaches: 0,
    Yellow_Pepper: 0,
    Green_Pepper: 0,
    Courgettes: 0,
    Tinned_Tomatos: 0,
    Chestnuts: 0,
    Wild_Mushrooms: 0,
    Truffle_Oil: 0,
    Paneer: 0,
    Naan_Bread: 0,
    Lentils: 0,
    Roasted_Vegetables: 0,
    Kidney_Beans: 0,
    Mixed_Grain: 0,
    Tahini: 0,
    Tortillas: 0,
    Udon_Noodles: 0,
    Cabbage: 0,
    Shiitake_Mushrooms: 0,
    Mirin: 0,
    Sesame_Seed_Oil: 0,
    Baguette: 0,
    Vine_Tomatoes: 0,
    Suet: 0,
    Swede: 0,
    Ham: 0,
    Oysters: 0,
    Stout: 0,
    Lard: 0,
    Lamb_Kidney: 0,
    Beef_Kidney: 0,
    Haddock: 0,
    Smoked_Haddock: 0,
    Brussels_Sprouts: 0,
    Raisins: 0,
    Currants: 0,
    Custard: 0,
    Mixed_Peel: 0,
    Redcurrants: 0,
    Blackberries: 0,
    Hazlenuts: 0,
    Braeburn_Apples: 0,
    Red_Food_Colouring: 0,
    Pink_Food_Colouring: 0,
    Blue_Food_Colouring: 0,
    Yellow_Food_Colouring: 0,
    Apricot_Jam: 0,
    Marzipan: 0,
    Almonds: 0,
    Black_Pudding: 0,
    Baked_Beans: 0,
    White_Flour: 0,
    Yeast: 0,
    Fruit_Mix: 0,
    Dried_Fruit: 0,
    Cherry: 0,
    Glace_Cherry: 0,
    Treacle: 0,
    Oatmeal: 0,
    Oats: 0,
    Egg: 0,
    Beef_Shin: 0,
    Bouquet_Garni: 0,
    Single_Cream: 0,
    Red_Wine_Jelly: 0,
    Apples: 0,
    Goats_Cheese: 0,
    Prosciutto: 0,
    Unsalted_Butter: 0,
    Brie: 0,
    Tarragon_Leaves: 0,
    Chives: 0,
    Pears: 0,
    White_Chocolate: 0,
    Star_Anise: 0,
    Tiger_Prawns: 0,
    Custard_Powder: 0,
    Desiccated_Coconut: 0,
    Frozen_Peas: 0,
    Minced_Pork: 0,
    Creamed_Corn: 0,
    // Sun-Dried_Tomatoes: 0,
    Dijon_Mustard: 0,
    Tabasco_Sauce: 0,
    Canola_Oil: 0,
    Cod: 0,
    Salt_Cod: 0,
    Ackee: 0,
    Jerk: 0,
    Ground_Beef: 0,
    Baby_Aubergine: 0,
    Paella_Rice: 0,
    Scotch_Bonnet: 0,
    Oxtail: 0,
    Broad_Beans: 0,
    Red_Snapper: 0,
    Malt_Vinegar: 0,
    Rice_Vinegar: 0,
    Water_Chestnut: 0,
    Tofu: 0,
    Doubanjiang: 0,
    Fermented_Black_Beans: 0,
    Scallions: 0,
    Sichuan_Pepper: 0,
    Wonton_Skin: 0,
    Starch: 0,
    Rice_wine: 0,
    Cooking_wine: 0,
    Duck_Sauce: 0,
    Gochujang: 0,
    Bean_Sprouts: 0,
    Noodles: 0,
    Wood_Ear_Mushrooms: 0,
    Dark_Rum: 0,
    Light_Rum: 0,
    Rum: 0,
    English_Muffins: 0,
    Muffins: 0,
    White_Wine_Vinegar: 0,
    Smoked_Salmon: 0,
    Mars_Bar: 0,
    Rice_Krispies: 0,
    Ancho_Chillies: 0,
    Almond_Milk: 0,
    Allspice: 0,
    Almond_Extract: 0,
    Tripe: 0,
    Goat_Meat: 0,
    Black_Beans: 0,
    Anchovy_Fillet: 0,
    Ras_el_hanout: 0,
    Filo_Pastry: 0,
    Orange_Blossom_Water: 0,
    Candied_Peel: 0,
    Grand_Marnier: 0,
    Sherry: 0,
    Rose_water: 0,
    Mixed_Spice: 0,
    Mincemeat: 0,
    Sweet_Potatoes: 0,
    Bread_Rolls: 0,
    Bun: 0,
    Potatoe_Buns: 0,
    Ground_Pork: 0,
    Pork_Chops: 0,
    Yukon_Gold_Potatoes: 0,
    Yellow_Onion: 0,
    Beef_Stock_Concentrate: 0,
    Chicken_Stock_Concentrate: 0,
    Persian_Cucumber: 0,
    Mayonnaise: 0,
    Sriracha: 0,
    Rhubarb: 0,
    Pita_Bread: 0,
    Bulgur_Wheat: 0,
    Quinoa: 0,
    Dill_Pickles: 0,
    Sesame_Seed_Burger_Buns: 0,
    Buns: 0,
    Iceberg_Lettuce: 0,
    Gherkin_Relish: 0,
    Cheese_Slices: 0,
    Shortening: 0,
    Warm_Water: 0,
    Boiling_Water: 0,
    Pickle_Juice: 0,
    Powdered_Sugar: 0,
    Kielbasa: 0,
    Polish_Sausage: 0,
    Sauerkraut: 0,
    Caraway_Seed: 0,
    Herring: 0,
    Jam: 0,
    Mulukhiyah: 0,
    Sushi_Rice: 0,
    Figs: 0,
    Cider: 0,
    Beetroot: 0,
    Sardines: 0,
    Ciabatta: 0,
    Buckwheat: 0,
}