export const countriesCodes = {
    // "DZ": "Algeria",
    // "AO": "Angola",
    "AR": "Argentina",
    "AU": "Australia",
    // "AT": "Austria",
    // "AZ": "Azerbaijan",
    // "BH": "Bahrain",
    "BD": "Bangladesh",
    // "BY": "Belarus",
    "BE": "Belgium",
    // "BO": "Bolivia",
    "BR": "Brazil",
    // "BG": "Bulgaria",
    // "BF": "Burkina Faso",
    // "KH": "Cambodia",
    // "CM": "Cameroon",
    "CA": "Canada",
    // "CL": "Chile",
    // "CN": "China",
    // "CO": "Colombia",
    // "CR": "Costa Rica",
    // "CI": "Cote D\"Ivoire",
    // "HR": "Croatia",
    // "CU": "Cuba",
    // "CZ": "Czech Republic",
    // "DK": "Denmark",
    // "DO": "Dominican Republic",
    // "EC": "Ecuador",
    // "EG": "Egypt",
    // "EE": "Estonia",
    // "ET": "Ethiopia",
    // "FI": "Finland",
    // "FR": "France",
    // "DE": "Germany",
    // "GH": "Ghana",
    // "GR": "Greece",
    // "GT": "Guatemala",
    // "HK": "Hong Kong",
    // "HU": "Hungary",
    // "IS": "Iceland",
    "IN": "India",
    // "ID": "Indonesia",
    // "IQ": "Iraq",
    // "IE": "Ireland",
    "IL": "Israel",
    // "IT": "Italy",
    "JP": "Japan",
    // "JO": "Jordan",
    // "KZ": "Kazakhstan",
    // "KE": "Kenya",
    // "KW": "Kuwait",
    // "LV": "Latvia",
    // "LB": "Lebanon",
    // "LY": "Libyan Arab Jamahiriya",
    // "LT": "Lithuania",
    // "LU": "Luxembourg",
    // "MO": "Macao",
    // "MG": "Madagascar",
    // "MW": "Malawi",
    // "MY": "Malaysia",
    // "ML": "Mali",
    // "MR": "Mauritania",
    "MX": "Mexico",
    // "MA": "Morocco",
    // "MZ": "Mozambique",
    // "MM": "Myanmar",
    // "NP": "Nepal",
    "NL": "Netherlands",
    // "NZ": "New Zealand",
    // "NG": "Nigeria",
    // "KP": "North korea",
    // "NO": "Norway",
    // "OM": "Oman",
    // "PK": "Pakistan",
    // "PA": "Panama",
    // "PY": "Paraguay",
    // "PE": "Peru",
    // "PH": "Philippines",
    "PL": "Poland",
    // "PT": "Portugal",
    "PR": "Puerto Rico",
    // "RO": "Romania",
    // "RU": "Russian Federation",
    // "SA": "Saudi Arabia",
    // "SN": "Senegal",
    // "RS": "Serbia",
    // "SG": "Singapore",
    // "SK": "Slovakia",
    // "SI": "Slovenia",
    // "SO": "Somalia",
    // "ZA": "South Africa",
    // "KR": "South Korea",
    // "ES": "Spain",
    // "LK": "Sri Lanka",
    // "SD": "Sudan",
    // "SE": "Sweden",
    // "CH": "Switzerland",
    // "TW": "Taiwan",
    // "TZ": "Tanzania",
    // "TH": "Thailand",
    // "TN": "Tunisia",
    "TR": "Turkey",
    // "TM": "Turkmenistan",
    // "UG": "Uganda",
    // "UA": "Ukraine",
    // "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    // "UY": "Uruguay",
    // "UZ": "Uzbekistan",
    // "VE": "Venezuela",
    "VN": "Vietnam",
    "ZM": "Zambia"
}

export const countriesConversions = () => {
    const countries = [];
    for (let key in countriesCodes) {
        const obj = { code: key, name: countriesCodes[key] }
        countries.push(obj)
    }
    
    return countries
}