import { Herobanner } from '@/components/Herobanner'
import { SidebarNavs } from '@/components/Sidebar'
import '@/styles/globals.css'
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { SessionProvider } from 'next-auth/react'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  const queryClient = new QueryClient()
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Dashboard Experience Using T.A.N.T.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <SidebarNavs />
      <Component {...pageProps} /> */}
      {/* session={pageProps.session} */}
      <SessionProvider>
        <Herobanner />
        <div className='flex flex-row gap-6'>
          <SidebarNavs />
          <Component {...pageProps} />
        </div>
      </SessionProvider>
      <ReactQueryDevtools />
    </QueryClientProvider>
  )
}
