import { Sidebar } from '@/components/Sidebar'
import '@/styles/globals.css'
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { SessionProvider } from 'next-auth/react'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  const queryClient = new QueryClient()
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Dashboard Experience Using T.A.N.T.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div 
        className='xs:block lg:flex flex-row gap-6 min-h-screen w-full'
        style={{
          background: `url(${"/abstract.jpg"})`,
          backgroundSize: "cover",
          backgroundBlendMode: "soft-light",
          backgroundRepeat: "no-repeat",
          opacity: ".9"
        }}
      >
        <Sidebar />
        <Component {...pageProps} />
      </div>
      {/* Photo by Markus Winkler: https://www.pexels.com/photo/white-paper-on-a-green-typewriter-12199409/ */}
      {/* Photo by Miguel Á. Padriñán: https://www.pexels.com/photo/close-up-shot-of-keyboard-buttons-2882634/ */}
{/* Photo by Steve Johnson: https://www.pexels.com/photo/multicolored-abstract-painting-1509534/ */}
      {/* <SessionProvider baseUrl='http://localhost:3000/'>
        <div className='flex flex-row gap-6'>
          <Sidebar />
          <Component {...pageProps} />
        </div>
      </SessionProvider> */}

      {/* <SidebarNavs />
      <Component {...pageProps} /> */}
      {/* session={pageProps.session} */}
      {/* <SessionProvider>
        <div className='flex flex-row gap-6'>
          <Component {...pageProps} />
        </div>
      </SessionProvider> */}
      <ReactQueryDevtools />
    </QueryClientProvider>
  )
}
