import '@/styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { ThemeProvider } from "styled-components"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { SessionProvider } from 'next-auth/react'
import Head from 'next/head'
// import { Header } from '@/components/header'
// import { Footer } from '@/components/footer'
import "@/styles/layout.css"
import { Header } from '@/layouts/header'
import { Footer } from '@/layouts/footer'
import { Navbar } from '@/components/navbar'
import "@/components/navbar/Navbar.css"
const theme = {
  colors: {
    primary: "#355C7D"
  }
}

export default function App({ Component, pageProps }) {
  // when custom layout is defined we then use that layout instead of what's been defined here globally
  if (Component.getLayout) {
    return Component.getLayout(<Component {...pageProps} />)
  }

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>NextJS Concepts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* session will reduce netwirk calls as this will be done from server side */}
      {/* Provider will reduce netwrok call in Client Side */}
      <SessionProvider session={pageProps.session}>
        <Navbar />
        <Component {...pageProps} />
      </SessionProvider>
      <Footer />
    </ThemeProvider>
  )
}
