import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Home.module.css'
import style from "@/styles/About.module.css"
import style2 from "@/styles/About.module.scss"

function About() {
  return (
    <>
      <Head>
        {/* <title>About Page</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >
        <h2 className={style.highlight}>Using Compoennt Level Styling!!</h2>
        <h3 className={style2.highlightScss}>Using Compoennt Level Styling!!</h3>
        <button className='btn btn-primary'>Does Nothing -- For UI Purposes Only</button>
        <h1 className={styles.title}>About Us</h1>
      </main>
    </>
  )
}

export default About