import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'
import { SidebarNavigation } from '@/components/MainNavigation'

const inter = Inter({ subsets: ['latin'] })

// its always a good practice to view this in build mode to see what will be deployed in procution mode and how app wqill behave before actual deployment takes place

// index.js will be treated as home routes by default
// nextJS uses file based routing system
// any file added into Pages folder will be treated as a destination for route page, which includes nested, dynamic, and static kind of pages
export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-row gap-4 bg-gray-400'>
        <SidebarNavigation />
        <h1>What What!!</h1>
      </main>
    </>
  )
}
