import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

// index.js will be treated as home routes by default
// nextJS uses file based routing system
// any file added into Pages folder will be treated as a destination for route page, which includes nested, dynamic, and static kind of pages
export default function Home() {
  const router = useRouter();

  const handleClick = () => {
      // by pushing it to router history stack we will ensure routes to this pushed route
      router.push("/product")

      // we can use "replace" which will mimic "replace" property used on "Link"
      // router.replace("/product")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href={"/blog"}>
          Blog
        </Link>
        <Link href={"/product"}>
          Products
        </Link>
        {/* usecase for rendering routes programatically after any action */}
        <button onClick={handleClick}>Place Order</button>
        <h1 className={styles.title}>Hello NextJS</h1>
        <p className={styles.description}>All System Gooooo NextJS</p>
        <div className={styles.description}>
          <p>All System Gooooo NextJS</p>
        </div>
      </main>
    </>
  )
}
