import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Home.module.css'

function About() {
  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Profile Page</h1>
      </main>
    </>
  )
}

export default About